### ISSUE TITLE
[FIXED] Turn off enemy names

### ISSUE THREAD

**Issue by Tarun430** [iBLiSSINYT/survivio-plus#389]
I feel like something good that could be added to this extension is the ability to turn off the visibility of enemy names, so that you do not see their names. I turned off everything except for the aimbot, so that it is not obvious when I play surviv with my friends during english. But they then ask me how I can see everyone's name. Please do something! Thank you!!!!!!!

**Comment by iBLiSSINYT** [comment]
[survivio-plus-master (3).zip](https://github.com/Kalaborative/survivio-plus/files/3082633/survivio-plus-master.3.zip)

Use this one if you don't want names always on. To turn on names hold shift ingame.

**Comment by Tarun430** [comment]
It doesn't let me add that one as an extension. It says manifest file is missing or unreadable

**Comment by iBLiSSINYT** [comment]
ok

Go into ur extension

Go into payload

Double click gameUpdate.js and open it somewhere where u can edit the text

Delete this line: window.gameVars.Input.Cheat.ShowNamesPressed = true;

Remember to save your file and reload the extension
