### ISSUE TITLE
We Got Pached

### ISSUE THREAD

**Issue by SheZCo** [iBLiSSINYT/survivio-plus#412]
Yea we got patched, zoom, aim, lasersight, everything isnt working for me as of 6:38 am. The Hack menu does show up but nothng works

**Comment by BeastModeOn3** [comment]
https://www.youtube.com/watch?v=2DA9P1Z-QtM
this is my way of fixing "Unauthorized extension use detected"
And now everything is patched

**Comment by iBLiSSINYT** [comment]
unfortunately we have 3 leprechauns here and the hack will not be updated until further notice. Not my fault, blame these fuckers instead.

**Comment by iBLiSSINYT** [comment]
However

**Comment by iBLiSSINYT** [comment]
However if you do want the hack, please contact my discord where I will be undergoing extensive verification.

**Comment by pilgrimoflight** [comment]
> However if you do want the hack, please contact my discord where I will be undergoing extensive verification.

Hey, where can we find your discord link ?

**Comment by iBLiSSINYT** [comment]
@iBLiSSINYT
